package GUI.major.floatingWindowHelper;

import GUI.major.MainWindow;
import java.awt.Component;

/**
 * This class is used for floating window
 *
 * @author Shu Liu
 */
public class FloatingWindow extends javax.swing.JDialog {

    private final MainWindow mainWindow;

    /**
     * Constructor
     *
     * @param mainWindow MainWindow instance
     * @param content component to be displayed in this floating window
     */
    public FloatingWindow(MainWindow mainWindow, Component content) {
        super(mainWindow, false);
        initComponents();
        this.mainWindow = mainWindow;
        add(content);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        mainWindow.floatingWindowClosed(getTitle());
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
