package GUI.ATDMHelper.summary;

import coreEngine.Helper.CEConst;
import coreEngine.Seed;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 * This dialog is used to select the type of the ATDM summary.
 *
 * @author Shu Liu
 */
public class SummaryTypeSelectionDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form SummaryTypeSelectionDialog
     *
     * @param parent parent frame
     * @param seed seed instance
     */
    public SummaryTypeSelectionDialog(java.awt.Frame parent, Seed seed) {
        super(parent, true);
        initComponents();

        //set starting position
        this.setLocationRelativeTo(this.getRootPane());

        DefaultComboBoxModel atdmSetModel = new javax.swing.DefaultComboBoxModel();
        for (int atdm = 0; atdm < seed.getValueInt(CEConst.IDS_ATDM_SET_NUM); atdm++) {
            atdmSetModel.addElement("ATDM Set #" + (atdm + 1));
        }
        atdmSetCB.setModel(atdmSetModel);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * Getter for return status
     *
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        atdmSingleRB = new javax.swing.JRadioButton();
        atdmSetCB = new javax.swing.JComboBox();
        atdmAllRB = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("ATDM Summary");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Please Select ATDM Summary Type"));

        buttonGroup1.add(atdmSingleRB);
        atdmSingleRB.setSelected(true);
        atdmSingleRB.setText("ATDM Single Set Summary (Scenarios Included In Set Only)");
        atdmSingleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atdmSingleRBActionPerformed(evt);
            }
        });

        atdmSetCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATDM Set #10" }));
        atdmSetCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                atdmSetCBItemStateChanged(evt);
            }
        });

        buttonGroup1.add(atdmAllRB);
        atdmAllRB.setText("ATDM Single Set Summary (All Scenarios)");
        atdmAllRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atdmAllRBActionPerformed(evt);
            }
        });

        jLabel1.setText(" ATDM Set: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atdmSingleRB)
                    .addComponent(atdmAllRB)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atdmSetCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(atdmSetCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atdmSingleRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atdmAllRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addGap(6, 6, 6))
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void atdmSetCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_atdmSetCBItemStateChanged
        atdmSetSelected = atdmSetCB.getSelectedIndex();
    }//GEN-LAST:event_atdmSetCBItemStateChanged

    private void atdmSingleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atdmSingleRBActionPerformed
        configSelection();
    }//GEN-LAST:event_atdmSingleRBActionPerformed

    private void atdmAllRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atdmAllRBActionPerformed
        configSelection();
    }//GEN-LAST:event_atdmAllRBActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * Getter for ATDM set selected
     *
     * @return ATDM set selected index
     */
    public int getAtdmSetSelected() {
        return atdmSetSelected;
    }

    /**
     * Getter for ATDM summary type
     *
     * @return selected ATDM summary type
     */
    public int getAtdmSummaryType() {
        return atdmSummaryType;
    }

    private void configSelection() {
        if (atdmSingleRB.isSelected()) {
            atdmSummaryType = ATDM_SINGLE_SET_SET_ONLY;
        }
        if (atdmAllRB.isSelected()) {
            atdmSummaryType = ATDM_SINGLE_SET_ALL;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton atdmAllRB;
    private javax.swing.JComboBox atdmSetCB;
    private javax.swing.JRadioButton atdmSingleRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    /**
     * ATDM summary type constant identifier
     */
    public final static int ATDM_SINGLE_SET_SET_ONLY = 0;

    /**
     * ATDM summary type constant identifier
     */
    public final static int ATDM_SINGLE_SET_ALL = 1;

    private int returnStatus = RET_CANCEL;

    private int atdmSetSelected = 0;

    private int atdmSummaryType = ATDM_SINGLE_SET_SET_ONLY;
}
