package GUI.major.outputPanel;

import GUI.major.MainWindow;
import GUI.major.tableHelper.SplitTableJPanel;
import GUI.seedEditAndIOHelper.ExcelAdapter;
import coreEngine.Seed;
import java.awt.Font;

/**
 * This class is the summary table across segments and for facility summary,
 *
 * @author Shu Liu
 */
public class FacilitySegmentSummaryPanel extends javax.swing.JPanel {

    private final FacilitySegmentJTableFirst facilitySegmentJTableFirst;

    private final FacilitySegmentJTableRest facilitySegmentJTableRest;

    private MainWindow mainWindow;

    private Seed seed;

    /**
     * Creates new form FacilitySegmentSummaryPanel
     */
    public FacilitySegmentSummaryPanel() {
        initComponents();

        facilitySegmentJTableFirst = new FacilitySegmentJTableFirst();
        facilitySegmentJTableRest = new FacilitySegmentJTableRest();
        SplitTableJPanel facilitySegmentSplitPanel = new SplitTableJPanel(facilitySegmentJTableFirst, facilitySegmentJTableRest);
        facilitySegmentSplitPanel.setDividerLocation(230);
        jPanel1.add(facilitySegmentSplitPanel);
    }

    /**
     * Show data for a particular seed, scenario and period
     *
     * @param seed seed to be displayed
     * @param scen index of scenario to be displayed
     * @param atdm ATDM set index
     */
    public void selectSeedScenATDM(Seed seed, int scen, int atdm) {
        this.seed = seed;
        facilitySegmentJTableFirst.selectSeed(seed);
        facilitySegmentJTableRest.selectSeedScenATDM(seed, scen, atdm);
        update();
    }

    /**
     * Setter for mainWindow connection
     *
     * @param mainWindow main window instance
     */
    public void setMainWindow(MainWindow mainWindow) {
        this.mainWindow = mainWindow;
    }

    /**
     * Update
     */
    public void update() {
        if (seed == null || !seed.isManagedLaneUsed()) {
            mlButton.setEnabled(false);
            cbButton.setEnabled(false);
            gpButton.setSelected(true);
        } else {
            mlButton.setEnabled(true);
            cbButton.setEnabled(true);
        }
        configModel();
        facilitySegmentJTableFirst.update();
        facilitySegmentJTableRest.update();
    }

    /**
     * Setter for table font
     *
     * @param newTableFont new table font
     */
    public void setTableFont(Font newTableFont) {
        facilitySegmentJTableFirst.setFont(newTableFont);
        facilitySegmentJTableFirst.setRowHeight(newTableFont.getSize() + 2);
        facilitySegmentJTableRest.setFont(newTableFont);
        facilitySegmentJTableRest.setRowHeight(newTableFont.getSize() + 2);
    }

    /**
     * Copy table to clipboard in excel format
     *
     * @return whether copy is successful
     */
    public String copyTable() {
        try {
            return (ExcelAdapter.copySplitTable(facilitySegmentJTableFirst, facilitySegmentJTableRest));
        } catch (Exception e) {
            return "Error when copy facilitySegment table " + e.toString();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        gpButton = new javax.swing.JRadioButton();
        mlButton = new javax.swing.JRadioButton();
        cbButton = new javax.swing.JRadioButton();

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroup1.add(gpButton);
        gpButton.setSelected(true);
        gpButton.setText("General Purpose Lanes");
        gpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpButtonActionPerformed(evt);
            }
        });
        jPanel2.add(gpButton);

        buttonGroup1.add(mlButton);
        mlButton.setText("Managed Lanes");
        mlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlButtonActionPerformed(evt);
            }
        });
        jPanel2.add(mlButton);

        buttonGroup1.add(cbButton);
        cbButton.setText("Combined");
        cbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cbButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpButtonActionPerformed
        configModel();
    }//GEN-LAST:event_gpButtonActionPerformed

    private void mlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlButtonActionPerformed
        configModel();
    }//GEN-LAST:event_mlButtonActionPerformed

    private void cbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbButtonActionPerformed
        configModel();
    }//GEN-LAST:event_cbButtonActionPerformed

    private void configModel() {
        if (gpButton.isSelected()) {
            facilitySegmentJTableRest.configModel(FacilitySegmentJTableRest.MODEL_GP);
        } else {
            if (mlButton.isSelected()) {
                facilitySegmentJTableRest.configModel(FacilitySegmentJTableRest.MODEL_ML);
            } else {
                facilitySegmentJTableRest.configModel(FacilitySegmentJTableRest.MODEL_CB);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cbButton;
    private javax.swing.JRadioButton gpButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton mlButton;
    // End of variables declaration//GEN-END:variables
}
