package GUI.ATDMHelper.hardShoulderRunning;

import GUI.ATDMHelper.rampMetering.RMContourJTableFirst;
import GUI.major.MainWindow;
import GUI.major.tableHelper.SplitTableJPanel;
import coreEngine.Helper.CEConst;
import coreEngine.Helper.CompressArray.CA2DInt;
import coreEngine.Seed;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Lake Trask
 */
public class ATDMHSRDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    private final RMContourJTableFirst contourJTableFirst;

    private final HSRContourJTableRest contourJTableRest;

    private final Seed seed;

    private float hsrCAF[];

    /**
     * Creates new form ATDMRMDialog
     *
     * @param parent
     * @param modal
     * @param seed
     * @param oldRampMeteringRate
     */
    public ATDMHSRDialog(java.awt.Dialog parent, boolean modal, Seed seed, CA2DInt oldRampMeteringRate) {
        super(parent, modal);
        initComponents();

        this.seed = seed;
        periodLabel.setText("<HTML><CENTER>Fill all<br>periods between:<br>(inclusive)");
        segmentLabel.setText("<HTML><Center>For all ramp<br>segments between:<br>(inclusive)");
        noteLabel.setText("<HTML><CENTER>Note: Color contour is based on the seed's D/C ratio.");
        DefaultComboBoxModel periodStartModel = new DefaultComboBoxModel();
        DefaultComboBoxModel periodEndModel = new DefaultComboBoxModel();
        for (int period = 0; period < seed.getValueInt(CEConst.IDS_NUM_PERIOD); period++) {
            periodStartModel.addElement("Period " + (period + 1));
            periodEndModel.addElement("Period " + (period + 1));
        }
        periodStartCB.setModel(periodStartModel);
        periodEndCB.setModel(periodEndModel);

        DefaultComboBoxModel segmentStartModel = new DefaultComboBoxModel();
        DefaultComboBoxModel segmentEndModel = new DefaultComboBoxModel();
        for (int seg = 0; seg < seed.getValueInt(CEConst.IDS_NUM_SEGMENT); seg++) {
            segmentStartModel.addElement("Segment " + (seg + 1));
            segmentEndModel.addElement("Segment " + (seg + 1));
        }

        segmentStartCB.setModel(segmentStartModel);
        segmentEndCB.setModel(segmentEndModel);

        contourJTableFirst = new RMContourJTableFirst(seed);
        contourJTableRest = new HSRContourJTableRest(seed);

        if (oldRampMeteringRate != null) {
            contourJTableRest.setHardShoulder(oldRampMeteringRate);
        }

        contourJTableFirst.setFont(MainWindow.getTableFont());
        contourJTableFirst.setRowHeight(MainWindow.getTableFont().getSize() + 2);
        contourJTableRest.setFont(MainWindow.getTableFont());
        contourJTableRest.setRowHeight(MainWindow.getTableFont().getSize() + 2);

        SplitTableJPanel contourSplitPanel = new SplitTableJPanel(contourJTableFirst, contourJTableRest);
        contourSplitPanel.setDividerLocation(160);
        jPanel2.add(contourSplitPanel);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        periodLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fillButton = new javax.swing.JButton();
        segmentLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        periodStartCB = new javax.swing.JComboBox();
        periodEndCB = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        segmentStartCB = new javax.swing.JComboBox();
        segmentEndCB = new javax.swing.JComboBox();
        fillValueComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        noteLabel = new javax.swing.JLabel();

        setTitle("ATDM Hard Shoulder Running");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel2.setToolTipText("test");
        jPanel2.setPreferredSize(new java.awt.Dimension(1020, 460));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        periodLabel.setText("Fill");

        jLabel3.setText("with");

        fillButton.setText("Fill");
        fillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillButtonActionPerformed(evt);
            }
        });

        segmentLabel.setText("jLabel4");

        jPanel1.setLayout(new java.awt.GridLayout(2, 1, 0, 3));

        periodStartCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(periodStartCB);

        periodEndCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(periodEndCB);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1, 0, 3));

        segmentStartCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(segmentStartCB);

        segmentEndCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(segmentEndCB);

        fillValueComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Off", "On" }));

        jButton1.setText("Configure Hard Shoulder Capacities");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        noteLabel.setText("Note: Color contour is based on seed's D/C ratio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(periodLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(segmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fillValueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fillButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addGap(2, 2, 2))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(noteLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton)
                            .addComponent(okButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(segmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(periodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(fillButton)
                                .addComponent(fillValueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel3});

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void fillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillButtonActionPerformed
//        try {
        int value = fillValueComboBox.getSelectedIndex();
        int startPeriod = Integer.parseInt(periodStartCB.getSelectedItem().toString().split(" ")[1]);
        int endPeriod = Integer.parseInt(periodEndCB.getSelectedItem().toString().split(" ")[1]);
        int startSegment = Integer.parseInt(segmentStartCB.getSelectedItem().toString().split(" ")[1]);
        int endSegment = Integer.parseInt(segmentEndCB.getSelectedItem().toString().split(" ")[1]);
        if (startPeriod > endPeriod && startSegment <= endSegment) {
            // Periods are not valid, segments are valid
            JOptionPane.showMessageDialog(this, "The start period must be before the end period.", "Error: Invalid Periods Specified", JOptionPane.ERROR_MESSAGE);
        } else if (startPeriod <= endPeriod && startSegment > endSegment) {
            // Periods are valid, segments are not valid
            JOptionPane.showMessageDialog(this, "The starting segment must be before the end segment.", "Error: Invalid Segments Specified", JOptionPane.ERROR_MESSAGE);
        } else if (startPeriod > endPeriod && startSegment > endSegment) {
            JOptionPane.showMessageDialog(this, "<HTML><CENTER>The start period must be before the end period.<br>The starting segment must be before the end segment.", "Error: Invalid Input", JOptionPane.ERROR_MESSAGE);
        } else { //input is correct
            contourJTableRest.fill(value, startPeriod, endPeriod, startSegment, endSegment);
        }
    }//GEN-LAST:event_fillButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HSRCapacityDialog hsrDialog = new HSRCapacityDialog(null, true);
        hsrDialog.setHardShouldCAFs(hsrCAF);
        hsrDialog.setLocationRelativeTo(null);
        hsrDialog.setVisible(true);
        if (hsrDialog.getReturnStatus()) {
            hsrCAF = hsrDialog.getHardShoulderCAFs();
        }
        hsrDialog.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     *
     * @return
     */
    public CA2DInt getHSRMatrix() {
        return contourJTableRest.getHardShoulder();
    }

    /**
     *
     * @param hsrMatrix
     */
    public void setHSRMatrix(CA2DInt hsrMatrix) {
        contourJTableRest.setHardShoulder(hsrMatrix);
    }

    /**
     *
     * @return
     */
    public float[] getHSRCAF() {
        return hsrCAF;
    }

    /**
     *
     * @param newVal
     */
    public void setHSRCAF(float[] newVal) {
        hsrCAF = newVal.clone();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton fillButton;
    private javax.swing.JComboBox fillValueComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox periodEndCB;
    private javax.swing.JLabel periodLabel;
    private javax.swing.JComboBox periodStartCB;
    private javax.swing.JComboBox segmentEndCB;
    private javax.swing.JLabel segmentLabel;
    private javax.swing.JComboBox segmentStartCB;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
